// ─── mapLayers.js — Basemap layer definitions ─────────────────────────────────
export const MAP_LAYERS = {
  Satellite: {
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attribution: "© Esri", icon: "Satellite",
    maxNativeZoom: 19,
  },
  Street: {
    url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution: "© OpenStreetMap", icon: "Street",
    maxNativeZoom: 19,
  },
  Terrain: {
    url: "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
    attribution: "© OpenTopoMap", icon: "Terrain",
    maxNativeZoom: 17,
  },
  Hillshade: {
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
    attribution: "© ESRI", icon: "Hillshade",
    maxNativeZoom: 19,
  },
  Contour: {
    url: "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
    attribution: "© OpenTopoMap contributors", icon: "Contour",
    maxNativeZoom: 17,
  },
  "Satellite + Labels": {
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    overlayUrl: "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}",
    attribution: "© Esri", icon: "SatLabels",
    maxNativeZoom: 19, overlayMaxNativeZoom: 19,
  },
  Dark: {
    url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
    attribution: "© CartoDB", icon: "Dark",
    maxNativeZoom: 19,
  },
  Light: {
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    attribution: "© CartoDB", icon: "Light",
    maxNativeZoom: 19,
  },
  "WMS – States demo": {
    type: "wms", url: "https://ahocevar.com/geoserver/wms",
    layers: "topp:states", format: "image/png", transparent: true,
    attribution: "GeoServer", icon: "WMS",
  },
};

// ─── menuDefs.js — Desktop menu bar definitions ───────────────────────────────
export const MENU_DEFS = {
  File: [
    { label: "Open KML…",          icon: "Upload",  action: "openKML" },
    { label: "Open KMZ / CSV…",    icon: "CSV",     action: "openExtra" },
    { label: "Open GeoJSON…",      icon: "GeoJSON", action: "openGeoJSON" },
    { divider: true },
    { label: "Export Drawings…",   icon: "Export",  action: "export" },
    { label: "Export as GeoJSON",  icon: "GeoJSON", action: "exportGeoJSON" },
    { divider: true },
    { label: "Reset / Clear All",  icon: "Reset",   action: "resetAll" },
  ],
  Edit: [
    { label: "Start Drawing",      icon: "Draw",    action: "startDraw" },
    { label: "Cancel Drawing",     icon: "Close",   action: "cancelDraw" },
    { divider: true },
    { label: "Start Measuring",    icon: "Measure", action: "startMeasure" },
    { label: "Stop Measuring",     icon: "Stop",    action: "stopMeasure" },
    { divider: true },
    { label: "Delete All Drawings",icon: "Trash",   action: "deleteDrawings" },
  ],
  View: [
    { label: "Satellite",           icon: "Satellite", action: "layerSatellite" },
    { label: "Street",              icon: "Street",    action: "layerStreet" },
    { label: "Terrain",             icon: "Terrain",   action: "layerTerrain" },
    { label: "Dark Mode",           icon: "Dark",      action: "layerDark" },
    { label: "Light Mode",          icon: "Light",     action: "layerLight" },
    { label: "Satellite + Labels",  icon: "SatLabels", action: "layerSatLabels" },
    { divider: true },
    { label: "Switch to 3D Globe",  icon: "Globe",     action: "show3D" },
    { divider: true },
    { label: "Toggle Auto Night",   icon: "Night",     action: "toggleNight" },
  ],
  Tools: [
    { label: "Draw Tool",           icon: "Draw",      action: "startDraw" },
    { label: "Measure Tool",        icon: "Measure",   action: "startMeasure" },
    { label: "Survey Tool",         icon: "Survey",    action: "toggleSurvey" },
    { divider: true },
    { label: "▶ Live Track Recorder", icon: "Record", action: "openTracker" },
    { divider: true },
    { label: "⛰ Elevation Profile", icon: "Mountain", action: "openElevation" },
    { label: "🧭 Compass Navigation",icon: "Compass",  action: "openCompassNav" },
    { divider: true },
    { label: "📴 Offline Maps",      icon: "Offline",  action: "openOffline" },
    { label: "🗺 Toggle Offline",    icon: "Offline",  action: "toggleOfflineMode" },
    { divider: true },
    { label: "3D Globe View",       icon: "Globe",     action: "show3D" },
  ],
  Add: [
    { label: "Add Marker",          icon: "Pin",      action: "drawMarker" },
    { label: "Add Path",            icon: "Path",     action: "drawPath" },
    { label: "Add Polygon",         icon: "Polygon",  action: "drawPoly" },
    { divider: true },
    { label: "Load KML File",       icon: "Upload",   action: "openKML" },
    { label: "Load KMZ / CSV",      icon: "CSV",      action: "openExtra" },
    { label: "Load GeoJSON",        icon: "GeoJSON",  action: "openGeoJSON" },
  ],
  Help: [
    { label: "About SurveyMap Pro", icon: "Info",     action: "about" },
    { label: "Keyboard Shortcuts",  icon: "Keyboard", action: "shortcuts" },
    { divider: true },
    { label: "OpenStreetMap ↗",     icon: "Link",     action: "osmLink" },
    { label: "Leaflet Docs ↗",      icon: "Link",     action: "leafletLink" },
  ],
};